-- Public-schema inventory => baseline DDL generator. READ-ONLY: catalog SELECTs only (pg_catalog / pg_get_*def).
-- Never reads table data. Secrets: any JWT literal inside a function body is replaced with 'REDACTED'.
--
-- Usage (against the database being captured; psql -At prints each ddl row, so stdout IS the baseline):
--   psql "$URL" -X -At -f scripts/schema-baseline/inventory.sql > prisma/baseline/<date>.sql
-- Row order = dependency order:
--   preamble -> extensions -> enums -> sequences -> tables(+inline PK/UNIQUE/CHECK) -> sequence ownership -> foreign keys
--   -> functions -> views/matviews (topological) -> indexes -> triggers -> RLS flags -> policies -> grants.
-- Out of scope (Supabase managed / documented in docs/BASELINE-CAPTURE.md): auth/storage/extensions/vault schemas, storage buckets,
--   object owners, default privileges, comments, extensions living outside public, sequence current values (data).
WITH
rel AS (
  SELECT c.oid, c.relname, c.relkind, c.relowner, c.reloptions, c.relacl, c.relrowsecurity, c.relforcerowsecurity
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND c.relkind IN ('r','v','m','S')
    AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.classid = 'pg_class'::regclass AND d.objid = c.oid AND d.deptype = 'e')
),
fn AS (
  SELECT p.oid, p.proname, p.proowner, p.proacl,
    quote_ident(n.nspname)||'.'||quote_ident(p.proname)||'('||oidvectortypes(p.proargtypes)||')' sig
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public' AND p.prokind IN ('f','p')
    AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.classid = 'pg_proc'::regclass AND d.objid = p.oid AND d.deptype = 'e')
),
vedge AS (
  SELECT DISTINCT c.oid v, rc.oid ref
  FROM pg_rewrite r JOIN pg_class c ON c.oid = r.ev_class
  JOIN pg_depend d ON d.classid = 'pg_rewrite'::regclass AND d.objid = r.oid AND d.refclassid = 'pg_class'::regclass
  JOIN pg_class rc ON rc.oid = d.refobjid
  WHERE c.oid IN (SELECT oid FROM rel WHERE relkind IN ('v','m')) AND rc.oid IN (SELECT oid FROM rel WHERE relkind IN ('v','m')) AND rc.oid <> c.oid
),
vrank AS (
  WITH RECURSIVE rk(oid, lvl) AS (
    SELECT oid, 0 FROM rel WHERE relkind IN ('v','m')
    UNION ALL SELECT e.v, rk.lvl + 1 FROM rk JOIN vedge e ON e.ref = rk.oid)
  SELECT oid, max(lvl) lvl FROM rk GROUP BY oid
),
roles(rname) AS (VALUES ('anon'),('authenticated'),('service_role'),('cfo_acceptance_reader'),('PUBLIC')),
racl AS (
  SELECT CASE WHEN r.relkind = 'S' THEN 'SEQUENCE' ELSE 'TABLE' END okind, coalesce(g.rolname, 'PUBLIC') role,
    'public.'||quote_ident(r.relname) obj, x.privilege_type priv
  FROM rel r CROSS JOIN LATERAL aclexplode(coalesce(r.relacl, acldefault((CASE WHEN r.relkind = 'S' THEN 's' ELSE 'r' END)::"char", r.relowner))) x
  LEFT JOIN pg_roles g ON g.oid = x.grantee
  WHERE coalesce(g.rolname, 'PUBLIC') IN (SELECT rname FROM roles)
  UNION ALL
  SELECT 'FUNCTION', coalesce(g.rolname, 'PUBLIC'), f.sig, x.privilege_type
  FROM fn f CROSS JOIN LATERAL aclexplode(coalesce(f.proacl, acldefault('f', f.proowner))) x
  LEFT JOIN pg_roles g ON g.oid = x.grantee
  WHERE coalesce(g.rolname, 'PUBLIC') IN (SELECT rname FROM roles)
),
rgrp AS (
  SELECT okind, role, obj, string_agg(priv, ', ' ORDER BY priv) privs FROM racl GROUP BY okind, role, obj
),
inv(ord, rnk, name, ddl) AS (
  SELECT 0, 0, '', $s$-- Generated by scripts/schema-baseline/inventory.sql (read-only catalog capture). Schema only, no data.
SET check_function_bodies = false;
SET search_path = public;
DO $r$ DECLARE x text; BEGIN
  FOREACH x IN ARRAY ARRAY['anon','authenticated','service_role','cfo_acceptance_reader'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = x) THEN EXECUTE format('CREATE ROLE %I NOLOGIN', x); END IF;
  END LOOP;
END $r$;$s$
  UNION ALL
  SELECT 10, 0, e.extname, format('CREATE EXTENSION IF NOT EXISTS %I WITH SCHEMA public;', e.extname)
  FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace WHERE n.nspname = 'public'
  UNION ALL
  SELECT 20, 0, t.typname, format($$DO $e$ BEGIN CREATE TYPE public.%I AS ENUM (%s); EXCEPTION WHEN duplicate_object THEN NULL; END $e$;$$,
    t.typname, (SELECT string_agg(quote_literal(enumlabel), ', ' ORDER BY enumsortorder) FROM pg_enum WHERE enumtypid = t.oid))
  FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typtype = 'e'
  UNION ALL
  SELECT 30, 0, c.relname, format('CREATE SEQUENCE IF NOT EXISTS public.%I AS %s INCREMENT BY %s MINVALUE %s MAXVALUE %s START WITH %s CACHE %s%s;',
    c.relname, format_type(s.seqtypid, NULL), s.seqincrement, s.seqmin, s.seqmax, s.seqstart, s.seqcache, CASE WHEN s.seqcycle THEN ' CYCLE' ELSE '' END)
  FROM rel c JOIN pg_sequence s ON s.seqrelid = c.oid WHERE c.relkind = 'S'
  UNION ALL
  SELECT 40, 0, c.relname, format(E'CREATE TABLE IF NOT EXISTS public.%I (\n  %s\n);', c.relname,
    (SELECT string_agg(x.colsql, E',\n  ' ORDER BY x.o) FROM (
       SELECT a.attnum::bigint o, format('%I %s%s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
         CASE WHEN a.attcollation <> 0 AND a.attcollation <> (SELECT typcollation FROM pg_type WHERE oid = a.atttypid)
              THEN ' COLLATE '||(SELECT quote_ident(collname) FROM pg_collation WHERE oid = a.attcollation) ELSE '' END,
         CASE WHEN a.attgenerated = 's' THEN ' GENERATED ALWAYS AS ('||pg_get_expr(d.adbin, d.adrelid)||') STORED'
              WHEN d.adbin IS NOT NULL THEN ' DEFAULT '||pg_get_expr(d.adbin, d.adrelid) ELSE '' END,
         CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END) colsql
       FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
       WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
       UNION ALL
       SELECT 100000 + row_number() OVER (ORDER BY co.contype, co.conname), format('CONSTRAINT %I %s', co.conname, pg_get_constraintdef(co.oid))
       FROM pg_constraint co WHERE co.conrelid = c.oid AND co.contype IN ('p','u','c')) x))
  FROM rel c WHERE c.relkind = 'r'
  UNION ALL
  SELECT 45, 0, c.relname||'.'||a.attname, format('ALTER SEQUENCE public.%I OWNED BY public.%I.%I;', s.relname, c.relname, a.attname)
  FROM pg_depend d JOIN rel s ON s.oid = d.objid AND s.relkind = 'S' JOIN rel c ON c.oid = d.refobjid
  JOIN pg_attribute a ON a.attrelid = d.refobjid AND a.attnum = d.refobjsubid
  WHERE d.classid = 'pg_class'::regclass AND d.refclassid = 'pg_class'::regclass AND d.deptype = 'a'
  UNION ALL
  SELECT 50, 0, '', format($$DO $fk$ DECLARE r record; BEGIN
  FOR r IN SELECT * FROM (VALUES
%s
  ) v(t, n, d) LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_constraint k WHERE k.conname = r.n AND k.conrelid = format('public.%%I', r.t)::regclass) THEN
      EXECUTE format('ALTER TABLE public.%%I ADD CONSTRAINT %%I %%s', r.t, r.n, r.d);
    END IF;
  END LOOP;
END $fk$;$$, string_agg(format('    (%L, %L, %L)', c.relname, co.conname, pg_get_constraintdef(co.oid)), E',\n' ORDER BY c.relname COLLATE "C", co.conname COLLATE "C"))
  FROM pg_constraint co JOIN rel c ON c.oid = co.conrelid WHERE co.contype = 'f' HAVING count(*) > 0
  UNION ALL
  SELECT 60, 0, f.sig, regexp_replace(pg_get_functiondef(f.oid), 'eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+', 'REDACTED', 'g')||';' FROM fn f
  UNION ALL
  SELECT 70, vr.lvl, c.relname,
    CASE c.relkind
      WHEN 'v' THEN format('CREATE OR REPLACE VIEW public.%I%s AS%s;', c.relname,
        CASE WHEN c.reloptions IS NOT NULL THEN ' WITH ('||array_to_string(c.reloptions, ', ')||')' ELSE '' END, E'\n'||rtrim(vdef.d, ';'))
      ELSE format('CREATE MATERIALIZED VIEW IF NOT EXISTS public.%I AS%s WITH DATA;', c.relname, E'\n'||rtrim(vdef.d, ';'))
    END
  FROM rel c JOIN vrank vr ON vr.oid = c.oid
  -- Round-trip fixup: in cfo_yaklasan_odeme the non-leading UNION branches keep the auto column label "?column?" in production
  -- (deparsed WITHOUT "AS"); re-parsing the plain text would label them "text" and deparse "AS text". Pinning "?column?" restores the exact stored tree.
  CROSS JOIN LATERAL (SELECT CASE WHEN c.relname = 'cfo_yaklasan_odeme'
      THEN regexp_replace(pg_get_viewdef(c.oid), $re$(\n\s+)('(?:GIRIS|Pazaryeri tahsilatı|Diğer tahsilat)'::text),$re$, $rp$\1\2 AS "?column?",$rp$, 'g')
      ELSE pg_get_viewdef(c.oid) END d) vdef
  WHERE c.relkind IN ('v','m')
  UNION ALL
  SELECT 80, 0, i.indexname, regexp_replace(i.indexdef, '^CREATE (UNIQUE )?INDEX ', 'CREATE \1INDEX IF NOT EXISTS ')||';'
  FROM pg_indexes i WHERE i.schemaname = 'public'
    AND NOT EXISTS (SELECT 1 FROM pg_constraint co WHERE co.conindid = (quote_ident(i.schemaname)||'.'||quote_ident(i.indexname))::regclass)
    AND (quote_ident(i.schemaname)||'.'||quote_ident(i.tablename))::regclass IN (SELECT oid FROM rel)
  UNION ALL
  SELECT 90, 0, t.tgname, regexp_replace(pg_get_triggerdef(t.oid), '^CREATE (CONSTRAINT )?TRIGGER', 'CREATE OR REPLACE \1TRIGGER')||';'
  FROM pg_trigger t JOIN rel c ON c.oid = t.tgrelid WHERE NOT t.tgisinternal
  UNION ALL
  SELECT 100, 0, 'enable', format($$DO $rls$ DECLARE t text; BEGIN
  FOREACH t IN ARRAY ARRAY[
%s
  ] LOOP EXECUTE format('ALTER TABLE public.%%I ENABLE ROW LEVEL SECURITY', t); END LOOP;
END $rls$;$$, string_agg(format('    %L', relname), E',\n' ORDER BY relname COLLATE "C"))
  FROM rel WHERE relkind = 'r' AND relrowsecurity HAVING count(*) > 0
  UNION ALL
  SELECT 101, 0, 'force', format($$DO $frls$ DECLARE t text; BEGIN
  FOREACH t IN ARRAY ARRAY[
%s
  ] LOOP EXECUTE format('ALTER TABLE public.%%I FORCE ROW LEVEL SECURITY', t); END LOOP;
END $frls$;$$, string_agg(format('    %L', relname), E',\n' ORDER BY relname COLLATE "C"))
  FROM rel WHERE relkind = 'r' AND relforcerowsecurity HAVING count(*) > 0
  UNION ALL
  SELECT 110, 0, '', format($$DO $pol$ DECLARE r record; BEGIN
  FOR r IN SELECT * FROM (VALUES
%s
  ) v(t, n, d) LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_policies p WHERE p.schemaname = 'public' AND p.tablename = r.t AND p.policyname = r.n) THEN EXECUTE r.d; END IF;
  END LOOP;
END $pol$;$$, string_agg(format('    (%L, %L, %L)', p.tablename, p.policyname,
    format('CREATE POLICY %I ON public.%I AS %s FOR %s TO %s%s%s', p.policyname, p.tablename, p.permissive, p.cmd,
      array_to_string(p.roles, ', '), coalesce(' USING ('||p.qual||')', ''), coalesce(' WITH CHECK ('||p.with_check||')', ''))),
    E',\n' ORDER BY p.tablename COLLATE "C", p.policyname COLLATE "C"))
  FROM pg_policies p WHERE p.schemaname = 'public' HAVING count(*) > 0
  UNION ALL
  SELECT 120, 0, 'schema:'||role, format('GRANT USAGE ON SCHEMA public TO %s;', role)
  FROM (SELECT coalesce(g.rolname, 'PUBLIC') role FROM pg_namespace n CROSS JOIN LATERAL aclexplode(n.nspacl) x LEFT JOIN pg_roles g ON g.oid = x.grantee
        WHERE n.nspname = 'public' AND x.privilege_type = 'USAGE') s WHERE role IN (SELECT rname FROM roles)
  UNION ALL
  SELECT 121, 0, 'revoke-tables', 'REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC, anon, authenticated, service_role, cfo_acceptance_reader;'
  UNION ALL
  SELECT 122, 0, 'revoke-sequences', 'REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC, anon, authenticated, service_role, cfo_acceptance_reader;'
  UNION ALL
  SELECT 123, 0, 'revoke-functions', 'REVOKE ALL ON FUNCTION '||string_agg(sig, E',\n  ' ORDER BY sig COLLATE "C")||E'\n  FROM PUBLIC, anon, authenticated, service_role, cfo_acceptance_reader;' FROM fn HAVING count(*) > 0
  UNION ALL
  SELECT 130, 0, okind||':'||role||':'||privs,
    format('GRANT %s ON %s %s TO %s;', privs, okind, string_agg(obj, E',\n  ' ORDER BY obj COLLATE "C"), role)
  FROM rgrp GROUP BY okind, role, privs
)
SELECT ddl FROM inv ORDER BY ord, rnk, name COLLATE "C"
