'use client';
import { useCallback,useEffect,useState } from 'react';
import type { StoredWork } from '@/lib/cfo-agent/workflow-store';
type Report={schedule:string;heartbeat:{lastSuccessAt:string;trigger:string;goals:{monthlyRevenueTargetUsd:number|null;targetTry:number|null;observedRevenueTry:number|null;revenueComplete:boolean;progressPct:number|null;capitalTry:number|null;cardDebtTry:number|null}}|null;lastFailureAt:string|null;items:(StoredWork&{id:string})[]};
const statusNames:Record<string,string>={research:'Araştırılıyor',pending_approval:'Onay bekliyor',approved:'Onaylandı · uygulama bekliyor',rejected:'Reddedildi',completed:'Sonuç bildirildi',needs_review:'Değişti · yeniden incele',resolved:'Sinyal artık görünmüyor',withdrawn:'Önceki öneri geri çekildi · doğrulama gerekli'};
const money=(v:number|null)=>v==null?'Henüz ölçülemedi':`${v.toLocaleString('tr-TR',{maximumFractionDigits:2})} TL`;
export default function WorkflowPanel(){const [report,setReport]=useState<Report|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[results,setResults]=useState<Record<string,string>>({});
  const load=useCallback(async()=>{const response=await fetch('/api/admin/ai-cfo/cycle',{cache:'no-store'});if(!response.ok)throw new Error('Çalışma kayıtları okunamadı.');setReport(await response.json());},[]);
  useEffect(()=>{const controller=new AbortController();fetch('/api/admin/ai-cfo/cycle',{cache:'no-store',signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error('Çalışma kayıtları okunamadı.');setReport(await response.json());}).catch(e=>{if(!controller.signal.aborted)setMessage(e.message);});return()=>controller.abort();},[]);
  async function act(body:unknown){setBusy(true);setMessage('');try{const response=await fetch('/api/admin/ai-cfo/cycle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.message??'Döngü tamamlanamadı. Son başarılı çalışma tarihi değişmedi.');setMessage(result.reason==='already_running'?'Döngü zaten çalışıyor.':'Kaydedildi.');await load();}catch(e){setMessage(e instanceof Error?e.message:'İşlem tamamlanamadı.');}finally{setBusy(false);}}
  return <div className="space-y-4"><button disabled={busy} className="rounded border px-4 py-2 disabled:opacity-50" onClick={()=>act({action:'run'})}>{busy?'Çalışıyor…':'Şimdi çalıştır'}</button><p aria-live="polite">{message}</p>
    <p>Son başarılı çalışma: {report?.heartbeat?new Date(report.heartbeat.lastSuccessAt).toLocaleString('tr-TR'):'Henüz doğrulanmadı — ilk döngüyü çalıştırın'}</p>
    {report?.lastFailureAt&&<p>Son başarısız deneme: {new Date(report.lastFailureAt).toLocaleString('tr-TR')}</p>}
    {report?.heartbeat&&<div className="rounded border p-4"><p>Aylık hedef: {report.heartbeat.goals.monthlyRevenueTargetUsd?.toLocaleString('tr-TR')} USD · {money(report.heartbeat.goals.targetTry)}</p>
      <p>Gözlenen son 30 gün cirosu: {money(report.heartbeat.goals.observedRevenueTry)} · {report.heartbeat.goals.revenueComplete?'Dönem tamam':'Dönem eksik; hedef ilerleme oranı hesaplanmaz'}</p>
      <p>Kayıtlı sermaye: {money(report.heartbeat.goals.capitalTry)} · Kart borcu: {money(report.heartbeat.goals.cardDebtTry)}</p><p>Kart borcu toplam borç değildir. Tam kâr ve toplam borç doğrulanmadan başarı iddiası üretilmez.</p></div>}
    <p>Öneriler hesap ve kaynaklarıyla kaydedilir. Sipariş miktarları araştırma senaryosudur. Onay bir öneriyi kabul eder; fiyatı değiştirmez, ödeme yapmaz veya satın alma taahhüdü oluşturmaz.</p>
    {report?.items.sort((a,b)=>a.item.priority-b.item.priority).map(work=><article key={work.id} className="rounded border p-4 space-y-2"><h2 className="font-semibold">P{work.item.priority} · {work.item.title}</h2><p>{statusNames[work.status]}</p><p>{work.item.proposal}</p>
      <p>Gereken nakit: {money(work.item.cashRequiredTry)} · Tahmini katkı: {money(work.item.expectedGainTry)}{work.item.suggestedUnits!=null?` · 60 günlük örnek stok miktarı: ${work.item.suggestedUnits}`:''}</p>
      <details><summary>Kaynaklar ve açık noktalar</summary><ul>{work.item.evidence.map((e,i)=><li key={i}>{e}</li>)}</ul><ul>{work.item.blockers.map((e,i)=><li key={i}>{e}</li>)}</ul></details>
      {work.result&&<p>Bildirilen sonuç: {work.result}</p>}
      {['research','pending_approval','needs_review','approved'].includes(work.status)&&<div className="space-y-2"><textarea aria-label={`${work.item.title} sonucu veya ret gerekçesi`} className="block w-full rounded border p-2" maxLength={2000} placeholder="Uygulama sonucu veya ret gerekçesi" value={results[work.id]??''} onChange={e=>setResults({...results,[work.id]:e.target.value})}/>
        {work.item.requiresApproval&&['pending_approval','needs_review'].includes(work.status)&&<button disabled={busy} className="mr-3 rounded border px-3 py-1" onClick={()=>act({action:'approve',id:work.id,revision:work.revision,result:results[work.id]??''})}>Öneriyi onayla</button>}
        {work.status!=='approved'&&<button disabled={busy} className="mr-3 rounded border px-3 py-1" onClick={()=>act({action:'reject',id:work.id,revision:work.revision,result:results[work.id]??''})}>Gerekçeyle reddet</button>}
        {(work.status==='approved'||work.status==='research'&&!work.item.requiresApproval)&&<button disabled={busy} className="rounded border px-3 py-1" onClick={()=>act({action:'complete',id:work.id,revision:work.revision,result:results[work.id]??''})}>{work.status==='research'?'Araştırma sonucunu kaydet':'Uygulama sonucunu kaydet'}</button>}</div>}
    </article>)}</div>;
}
