'use client';
import { useCallback,useEffect,useState } from 'react';
import type { StoredWork } from '@/lib/cfo-agent/workflow-store';
import type { CycleDiagnostic } from '@/lib/cfo-agent/workflow-diagnostics';
import type { CycleAgenda } from '@/lib/cfo-agent/workflow-memory';
import { TOPIC_NAMES } from '@/lib/cfo-agent/workflow-topics';
import type { DebtForecast } from '@/lib/cfo-agent/debt-forecast';
type Report={schedule:string;heartbeat:{lastSuccessAt:string;trigger:string;agenda?:CycleAgenda;orderGate?:{open:boolean};debtForecast?:DebtForecast;goals:{monthlyRevenueTargetUsd:number|null;targetTry:number|null;observedRevenueTry:number|null;revenueComplete:boolean;progressPct:number|null;capitalTry:number|null;cardDebtTry:number|null;totalDebtTry:number|null}}|null;lastFailureAt:string|null;lastFailure:CycleDiagnostic|null;items:(StoredWork&{id:string})[]};
const statusNames:Record<string,string>={research:'Araştırılıyor',pending_approval:'Onay bekliyor',approved:'Onaylandı · uygulama bekliyor',rejected:'Reddedildi',completed:'Sonuç bildirildi',needs_review:'Değişti · yeniden incele',resolved:'Sinyal artık görünmüyor',withdrawn:'Önceki öneri geri çekildi · doğrulama gerekli'};
const money=(v:number|null)=>v==null?'Henüz ölçülemedi':`${v.toLocaleString('tr-TR',{maximumFractionDigits:2})} TL`;
export default function WorkflowPanel(){const [report,setReport]=useState<Report|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[results,setResults]=useState<Record<string,string>>({});
  const [budget,setBudget]=useState({interestMonthlyTry:'',otherMonthlyTry:'',cashReserveTry:'',settlementDays:''}),[verified,setVerified]=useState(false);
  const load=useCallback(async()=>{const response=await fetch('/api/admin/ai-cfo/cycle',{cache:'no-store'});if(!response.ok)throw new Error('Çalışma kayıtları okunamadı.');setReport(await response.json());},[]);
  useEffect(()=>{const controller=new AbortController();fetch('/api/admin/ai-cfo/cycle',{cache:'no-store',signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error('Çalışma kayıtları okunamadı.');setReport(await response.json());}).catch(e=>{if(!controller.signal.aborted)setMessage(e.message);});return()=>controller.abort();},[]);
  async function act(body:unknown){setBusy(true);setMessage('');try{const response=await fetch('/api/admin/ai-cfo/cycle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.message??'Döngü tamamlanamadı. Son başarılı çalışma tarihi değişmedi.');setMessage(result.reason==='already_running'?'Döngü zaten çalışıyor.':'Kaydedildi.');await load();}catch(e){setMessage(e instanceof Error?e.message:'İşlem tamamlanamadı.');try{await load();}catch{} }finally{setBusy(false);}}
  const active=report?.items.filter(work=>!['completed','resolved','withdrawn','rejected'].includes(work.status)).sort((a,b)=>a.item.priority-b.item.priority)??[];
  const focus=active.filter(work=>report?.heartbeat?.agenda?.focusKeys.includes(work.item.key)??true);
  return <div className="space-y-4"><button disabled={busy} className="rounded border px-4 py-2 disabled:opacity-50" onClick={()=>act({action:'run'})}>{busy?'Çalışıyor…':'Şimdi çalıştır'}</button><p aria-live="polite">{message}</p>
    <p>Son başarılı çalışma: {report?.heartbeat?new Date(report.heartbeat.lastSuccessAt).toLocaleString('tr-TR'):'Henüz doğrulanmadı — ilk döngüyü çalıştırın'}</p>
    {report?.lastFailureAt&&<p>Son başarısız deneme: {new Date(report.lastFailureAt).toLocaleString('tr-TR')}{report.lastFailure?` · ${report.lastFailure.stage} · ${report.lastFailure.code}${report.lastFailure.databaseCode?' · '+report.lastFailure.databaseCode:''}`:''}</p>}
    {report?.heartbeat?.agenda&&<div className="rounded border p-4"><p>Bu çalışma: {TOPIC_NAMES[report.heartbeat.agenda.topic]}</p>
      <p>Sonraki çalışma: {TOPIC_NAMES[report.heartbeat.agenda.nextTopic]}</p><p>İncelenen yeni/değişmiş cevap: {report.heartbeat.agenda.answersReviewed.length}</p>
      {report.heartbeat.agenda.unchangedCycles>=2&&<p>Beklenen veri değişmedi; diğer hedef işlerine geçiliyor.</p>}<a href="/cfo/defter" className="underline">Çalışma özeti ve devam planı →</a></div>}
    {report?.heartbeat&&<div className="rounded border p-4"><p>Aylık hedef: {report.heartbeat.goals.monthlyRevenueTargetUsd?.toLocaleString('tr-TR')} USD · {money(report.heartbeat.goals.targetTry)}</p>
      <p>Gözlenen son 30 gün cirosu: {money(report.heartbeat.goals.observedRevenueTry)} · {report.heartbeat.goals.revenueComplete?'Dönem tamam':'Dönem eksik; hedef ilerleme oranı hesaplanmaz'}</p>
      <p>Kayıtlı sermaye: {money(report.heartbeat.goals.capitalTry)} · Kart borcu: {money(report.heartbeat.goals.cardDebtTry)}</p><p>Defterdeki toplam borç: {money(report.heartbeat.goals.totalDebtTry)}</p><p>Bu değerler son kayıtlı kaynaklardan okunur. Kart borcu toplam borcun yerine kullanılmaz. Tam kâr ve kaynak tazeliği doğrulanmadan başarı iddiası üretilmez.</p></div>}
    <p>Öneriler hesap ve kaynaklarıyla kaydedilir. Sipariş miktarları araştırma senaryosudur. Onay bir öneriyi kabul eder; fiyatı değiştirmez, ödeme yapmaz veya satın alma taahhüdü oluşturmaz.</p>
    {report?.heartbeat?.debtForecast&&<div className="rounded border p-4 space-y-2"><p>Yeni sipariş: {report.heartbeat.orderGate?.open?'Borç eşiği geçildi; kâr ve öz nakit kontrolü gerekli':'Kapalı · toplam borç 5 milyon TL altına inmeli'}</p>
      <p>Tahmini sipariş tarihi: {report.heartbeat.debtForecast.estimatedOrderDate??(report.heartbeat.debtForecast.status==='not_reached'?'Mevcut stok ve ödeme ufkunda eşiğe ulaşılamıyor':'Veri eksik; tarih hesaplanamıyor')}</p>
      <p>Geçmiş kayıtlı 30 günlük ciro: {money(report.heartbeat.debtForecast.historicalMonthlyRevenueTry)} · {report.heartbeat.debtForecast.historicalComplete?'Tam pencere':'Eksik pencere'}</p>
      <details><summary>Hesap varsayımları ve eksikler</summary><ul>{[...report.heartbeat.debtForecast.missing,...report.heartbeat.debtForecast.assumptions].map((text,i)=><li key={i}>{text}</li>)}</ul></details>
      <details><summary>Tarih hesabı için bütçe bilgisi gir</summary><p className="my-2">Bu girdiler kullanıcı beyanı olarak kaydedilir ve 7 gün sonra yeniden teyit gerekir. Sabit gider ve takvim ayrıca okunur.</p>
        {([['interestMonthlyTry','Vergi ve ücret dahil aylık toplam faiz (TL)'],['otherMonthlyTry','Sabit gider/takvim dışında aylık diğer çıkış (TL)'],['cashReserveTry','Korunacak nakit tamponu (TL)'],['settlementDays','İhtiyatlı tahsilat süresi (gün)']] as const).map(([key,label])=><label key={key} className="block my-2">{label}<input type="number" min="0" required className="block rounded border p-2" value={budget[key]} onChange={e=>setBudget({...budget,[key]:e.target.value})}/></label>)}
        <label className="block my-2"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/> Mevcut stok bedeli ödenmiş; bu bütçe beyanı diğer aylık çıkışları kapsıyor.</label>
        <button disabled={busy||!verified||Object.values(budget).some(v=>v.trim()===''||!Number.isFinite(Number(v))||Number(v)<0)} className="rounded border p-2" onClick={()=>act({action:'forecast-budget',...Object.fromEntries(Object.entries(budget).map(([k,v])=>[k,Number(v)])),verified:true})}>Bütçeyi kaydet ve yeniden hesapla</button>
      </details></div>}
    <p className="rounded border p-4"><a href="/cfo/kazananlar#ithalat" className="underline">İthalat ve gelecek sipariş planlayıcısı →</a><br/>Adaylar, parti durumları, retler ve notlar burada birlikte izlenir.</p>
    <h2 className="font-semibold">Bu çalışmanın öncelikli işleri</h2>
    {focus.map(work=><article key={work.id} className="rounded border p-4 space-y-2"><h2 className="font-semibold">P{work.item.priority} · {work.item.title}</h2><p>{statusNames[work.status]}</p><p>{work.item.proposal}</p>{work.item.plannerPath&&<a href={work.item.plannerPath} className="underline">Planlayıcıdaki kayıt ve kararlar →</a>}
      <p>Gereken nakit: {money(work.item.cashRequiredTry)} · Tahmini katkı: {money(work.item.expectedGainTry)}{work.item.suggestedUnits!=null?` · 60 günlük örnek stok miktarı: ${work.item.suggestedUnits}`:''}</p>
      <details><summary>Kaynaklar ve açık noktalar</summary><ul>{work.item.evidence.map((e,i)=><li key={i}>{e}</li>)}</ul><ul>{work.item.blockers.map((e,i)=><li key={i}>{e}</li>)}</ul></details>
      {work.result&&<p>Bildirilen sonuç: {work.result}</p>}
      {['research','pending_approval','needs_review','approved'].includes(work.status)&&<div className="space-y-2"><textarea aria-label={`${work.item.title} sonucu veya ret gerekçesi`} className="block w-full rounded border p-2" maxLength={2000} placeholder="Uygulama sonucu veya ret gerekçesi" value={results[work.id]??''} onChange={e=>setResults({...results,[work.id]:e.target.value})}/>
        {work.item.requiresApproval&&['pending_approval','needs_review'].includes(work.status)&&<button disabled={busy} className="mr-3 rounded border px-3 py-1" onClick={()=>act({action:'approve',id:work.id,revision:work.revision,result:results[work.id]??''})}>Öneriyi onayla</button>}
        {work.status!=='approved'&&<button disabled={busy} className="mr-3 rounded border px-3 py-1" onClick={()=>act({action:'reject',id:work.id,revision:work.revision,result:results[work.id]??''})}>Gerekçeyle reddet</button>}
        {(work.status==='approved'||work.status==='research'&&!work.item.requiresApproval)&&<button disabled={busy} className="rounded border px-3 py-1" onClick={()=>act({action:'complete',id:work.id,revision:work.revision,result:results[work.id]??''})}>{work.status==='research'?'Araştırma sonucunu kaydet':'Uygulama sonucunu kaydet'}</button>}</div>}
    </article>)}
    <details className="rounded border p-4"><summary>Diğer açık işler ({active.length-focus.length})</summary><ul>{active.filter(work=>!focus.includes(work)).map(work=><li key={work.id} className="my-2">P{work.item.priority} · {work.item.title}<p>{work.item.proposal}</p>{work.item.plannerPath&&<a href={work.item.plannerPath} className="underline">Planlayıcıdaki kayıt ve kararlar →</a>}</li>)}</ul><p>Bu işler korunur; konu sırası geldiğinde öncelikli listeye alınır.</p></details>
  </div>;
}
