-- CFO disiplin altyapısı: snapshot zaman serisi, karar kuyruğu, log taksonomisi.
--
-- Neden: 27.08.2026 incelemesi üç yapısal boşluk gösterdi.
--   1) cfo_snapshot 0 satır — zaman serisi yok, "geçen haftaya göre" sorulamıyor.
--   2) 31 aday ürünün 29'u "inceleniyor", 0 karar — listeler birikiyor, süzülmüyor.
--   3) cfo_change_log.area'da 63 farklı değer — çünkü alan (nakit) ile kayıt türü
--      (bulgu) aynı kolona yazılmış. Log sorgulanamaz hâlde.

-- ═══════════════════════════════════════════════════════════════════
-- 1) AJANIN ELLE AÇTIĞI TABLOLAR — migration geçmişine alınıyor
-- ═══════════════════════════════════════════════════════════════════
-- Bu ikisi Supabase'de doğrudan oluşturulmuştu; repoda yoktu. Sıfırdan kurulan
-- bir ortamda oluşmuyorlardı. IF NOT EXISTS ile canlıda no-op.

CREATE TABLE IF NOT EXISTS "cfo_product_candidate" (
    "id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "found_at"           DATE NOT NULL DEFAULT CURRENT_DATE,
    "source"             TEXT,
    "product_name"       TEXT NOT NULL,
    "category"           TEXT,
    "sku"                TEXT,
    "sale_price_try"     NUMERIC,
    "unit_cost_try"      NUMERIC,
    "gross_margin_pct"   NUMERIC,
    "units_needed_monthly" NUMERIC,
    "market_evidence"    TEXT,
    "competition"        TEXT,
    "entry_capital_try"  NUMERIC,
    "concentration_risk" TEXT,
    "verdict"            TEXT NOT NULL DEFAULT 'inceleniyor',
    "verdict_reason"     TEXT,
    "updated_at"         TIMESTAMPTZ NOT NULL DEFAULT now(),
    "created_at"         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "cfo_dead_stock_finding" (
    "id"                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "found_at"            DATE NOT NULL DEFAULT CURRENT_DATE,
    "sku"                 TEXT,
    "product_name"        TEXT,
    "stock_qty"           INTEGER,
    "days_idle"           INTEGER,
    "tied_capital_try"    NUMERIC,
    "reason_code"         TEXT,
    "reason_evidence"     TEXT,
    "action_taken"        TEXT,
    "action_applied_at"   TIMESTAMPTZ,
    "released_capital_try" NUMERIC,
    "status"              TEXT NOT NULL DEFAULT 'acik',
    "updated_at"          TIMESTAMPTZ NOT NULL DEFAULT now(),
    "created_at"          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ═══════════════════════════════════════════════════════════════════
-- 2) LOG TAKSONOMİSİ — iki ekseni ayır
-- ═══════════════════════════════════════════════════════════════════
-- area = KONU (nakit, stok, kart…). kind = KAYIT TÜRÜ (bulgu, duzeltme, karar…).
-- Eskiden ikisi de area'ya yazılıyordu; bu yüzden "nakit tarafında ne değişti"
-- sorgulanamıyordu. Kayıt türü yazılmış satırlarda konu hiç kaydedilmemiş —
-- o satırlarda area 'diger' olur, tür kind'a taşınır. Veri uydurmuyoruz.

ALTER TABLE "cfo_change_log" ADD COLUMN IF NOT EXISTS "kind" TEXT;

-- Aşağıdaki UPDATE'ler 470 satırın area değerini yeniden yazıyor. Eşleme tablosunda
-- bir hata varsa geri dönebilmek için orijinali sakla. "Eski değer silinmez" kuralı
-- burada da geçerli.
CREATE TABLE IF NOT EXISTS "cfo_change_log_area_yedek" AS
SELECT id, area AS area_orijinal, now() AS yedeklendi FROM "cfo_change_log";

-- Önce büyük/küçük harf ve Türkçe karakter farklarını kaldır (anlam kaybı yok).
UPDATE "cfo_change_log"
   SET area = lower(translate(area, 'çğıİöşüÇĞÖŞÜ', 'cgiiosucgosu'));

-- Kayıt türü olarak yazılmış değerleri kind'a taşı.
UPDATE "cfo_change_log" SET "kind" = area, area = 'diger'
 WHERE area IN ('bulgu','duzeltme','karar','aksiyon','analiz','teyit','celiski',
                'arastirma','senaryo','onay','model','plan','cfo_oz_elestiri');

-- Kalan konu değerlerini sabit sözlüğe eşle.
UPDATE "cfo_change_log" SET area = CASE area
    WHEN 'kmh'             THEN 'nakit'
    WHEN 'likidite'        THEN 'nakit'
    WHEN 'odeme'           THEN 'nakit'
    WHEN 'ortak_cari'      THEN 'nakit'
    WHEN 'ozkaynak'        THEN 'nakit'
    WHEN 'sabit_gider'     THEN 'nakit'
    WHEN 'borc'            THEN 'kredi'
    WHEN 'finansman'       THEN 'kredi'
    WHEN 'ithalat'         THEN 'gumruk'
    WHEN 'kanal'           THEN 'satis'
    WHEN 'kalite'          THEN 'urun'
    WHEN 'seo'             THEN 'alfashome'
    WHEN 'trafik'          THEN 'alfashome'
    WHEN 'altyapi'         THEN 'iotomasyon'
    WHEN 'supabase'        THEN 'iotomasyon'
    WHEN 'sistem'          THEN 'iotomasyon'
    WHEN 'ayar'            THEN 'iotomasyon'
    WHEN 'soyluelektronik' THEN 'satis'
    WHEN 'hedef'           THEN 'strateji'
    WHEN 'firsat'          THEN 'strateji'
    WHEN 'ekim'            THEN 'strateji'
    WHEN 'cevap'           THEN 'soru'
    WHEN 'taksonomi'       THEN 'kural'
    WHEN 'gunluk_gorev'    THEN 'kural'
    WHEN 'politika'        THEN 'kural'
    WHEN 'kur'             THEN 'veri'
    WHEN 'hukuk'           THEN 'gumruk'
    ELSE area
END;

-- Sözlükte olmayan ne kaldıysa 'diger'e düşür (kayıp yok: item/note el değmemiş).
UPDATE "cfo_change_log" SET area = 'diger'
 WHERE area NOT IN ('nakit','banka','kart','kredi','alacak','gumruk','maliyet','marj',
                    'fiyat','satis','stok','olu_stok','urun','siparis','alfashome',
                    'iotomasyon','veri','strateji','soru','kural','risk','erisim',
                    'guvenlik','not','diger');

ALTER TABLE "cfo_change_log" DROP CONSTRAINT IF EXISTS "cfo_change_log_area_check";
ALTER TABLE "cfo_change_log" ADD CONSTRAINT "cfo_change_log_area_check" CHECK (
  area IN ('nakit','banka','kart','kredi','alacak','gumruk','maliyet','marj',
           'fiyat','satis','stok','olu_stok','urun','siparis','alfashome',
           'iotomasyon','veri','strateji','soru','kural','risk','erisim',
           'guvenlik','not','diger')
);

ALTER TABLE "cfo_change_log" DROP CONSTRAINT IF EXISTS "cfo_change_log_kind_check";
ALTER TABLE "cfo_change_log" ADD CONSTRAINT "cfo_change_log_kind_check" CHECK (
  "kind" IS NULL OR "kind" IN ('bulgu','duzeltme','karar','aksiyon','analiz',
                               'teyit','celiski','arastirma','senaryo','onay',
                               'model','plan','cfo_oz_elestiri')
);

CREATE INDEX IF NOT EXISTS "cfo_change_log_kind_idx" ON "cfo_change_log"("kind");

-- ═══════════════════════════════════════════════════════════════════
-- 3) SNAPSHOT — tek komutla, tek tanımla
-- ═══════════════════════════════════════════════════════════════════
-- Tanımlar lib/cfo/engine.ts:364 ile BİREBİR aynı olmalı:
--   narrowWorth = netCash + bekleyenAlacak + satılabilirStok - kartBorcu - krediErkenKapama
--   wideWorth   = narrowWorth + yoldakiStok + blokeStok
-- Motor değişirse bu fonksiyon da değişir. İkisi ayrışırsa panodaki rakam ile
-- zaman serisi çelişir; bu sessiz bir hata olur, o yüzden burada yazıyor.

CREATE OR REPLACE FUNCTION cfo_take_snapshot(p_note TEXT DEFAULT NULL)
RETURNS "cfo_snapshot"
LANGUAGE plpgsql
AS $$
DECLARE
  v_usd NUMERIC; v_cash NUMERIC; v_used_kmh NUMERIC; v_card NUMERIC;
  v_loan NUMERIC; v_recv NUMERIC; v_sellable NUMERIC; v_blocked NUMERIC;
  v_transit NUMERIC; v_narrow NUMERIC; v_wide NUMERIC; v_row "cfo_snapshot";
BEGIN
  SELECT COALESCE(NULLIF("usdTryRate", 0), 1),
         COALESCE("stockCostUsd", 0),
         COALESCE("blockedStockUsd", 0)
    INTO v_usd, v_sellable, v_blocked
    FROM "cfo_settings" LIMIT 1;
  IF v_usd IS NULL THEN v_usd := 1; v_sellable := 0; v_blocked := 0; END IF;
  v_sellable := v_sellable * v_usd;
  v_blocked  := v_blocked  * v_usd;

  -- Bakiyesi bilinmeyen banka sayılmaz (motor da saymıyor — muhafazakâr).
  SELECT COALESCE(SUM("balanceTry"), 0),
         COALESCE(SUM(CASE WHEN "balanceTry" < 0 THEN -"balanceTry" ELSE 0 END), 0)
    INTO v_cash, v_used_kmh
    FROM "cfo_bank_account" WHERE "isActive" AND "balanceTry" IS NOT NULL;

  SELECT COALESCE(SUM(COALESCE("totalDebtTry", "statementDebtTry")), 0)
    INTO v_card FROM "cfo_credit_card" WHERE "isActive";

  SELECT COALESCE(SUM("earlyPayoffTry"), 0)
    INTO v_loan FROM "cfo_loan" WHERE status::text = 'AKTIF';

  SELECT COALESCE(SUM("amountTry"), 0)
    INTO v_recv FROM "cfo_receivable" WHERE NOT "isCollected";

  SELECT COALESCE(SUM(COALESCE("totalCostUsd", 0)), 0) * v_usd
    INTO v_transit FROM "cfo_import_project"
   WHERE status::text IN ('YOLDA', 'GUMRUKTE');

  v_narrow := v_cash + v_recv + v_sellable - v_card - v_loan;
  v_wide   := v_narrow + v_transit + v_blocked;

  INSERT INTO "cfo_snapshot" (
      "id", "takenAt", "netWorthTry", "netWorthUsd", "wideWorthTry", "wideWorthUsd",
      "cashTry", "receivablesTry", "stockTry", "debtTry", "usdTryRate", "note")
  VALUES (
      gen_random_uuid()::text, now(),
      round(v_narrow, 2), round(v_narrow / v_usd, 2),
      round(v_wide, 2),   round(v_wide / v_usd, 2),
      round(v_cash, 2), round(v_recv, 2),
      round(v_sellable + v_blocked + v_transit, 2),
      round(v_used_kmh + v_card + v_loan, 2),
      v_usd, p_note)
  RETURNING * INTO v_row;

  RETURN v_row;
END $$;

COMMENT ON FUNCTION cfo_take_snapshot(TEXT) IS
  'Günlük servet fotoğrafı. Tanımlar lib/cfo/engine.ts:364 ile aynı tutulmalı.';

-- Günde birden fazla çağrılırsa son fotoğraf geçerlidir; hiçbiri silinmez.
CREATE OR REPLACE VIEW "cfo_snapshot_gunluk" AS
SELECT DISTINCT ON (("takenAt")::date) ("takenAt")::date AS gun, *
  FROM "cfo_snapshot" ORDER BY ("takenAt")::date DESC, "takenAt" DESC;

-- Dün ve 7 gün önceye göre fark — raporun "yön" satırı buradan gelir.
CREATE OR REPLACE VIEW "cfo_snapshot_delta" AS
WITH g AS (SELECT * FROM "cfo_snapshot_gunluk")
SELECT
  b.gun,
  b."netWorthUsd",
  b."netWorthUsd" - d."netWorthUsd" AS dune_gore_usd,
  b."netWorthUsd" - h."netWorthUsd" AS haftaya_gore_usd,
  b."cashTry"     - d."cashTry"     AS dune_gore_nakit_try,
  b."debtTry"     - d."debtTry"     AS dune_gore_borc_try,
  b."usdTryRate"
FROM g b
LEFT JOIN g d ON d.gun = b.gun - 1
LEFT JOIN g h ON h.gun = b.gun - 7
ORDER BY b.gun DESC;

-- ═══════════════════════════════════════════════════════════════════
-- 4) KARAR KUYRUĞU — biriken listelere çıkış kapısı
-- ═══════════════════════════════════════════════════════════════════
-- Sorun: aday/bulgu/soru açılıyor, hiç kapanmıyor. Bu görünüm "kaç gündür
-- bekliyor" bilgisini tek yerde verir; 3 günü geçen her satır karara zorlanır.

CREATE OR REPLACE VIEW "cfo_bekleyen_karar" AS
  SELECT 'aday'::text AS tur, id::text AS kayit_id,
         product_name AS baslik, verdict AS durum,
         found_at AS acilis, (CURRENT_DATE - found_at) AS bekleme_gun
    FROM "cfo_product_candidate"
   WHERE verdict IN ('inceleniyor', 'maliyet_bekliyor')
UNION ALL
  SELECT 'olu_stok', id::text,
         COALESCE(product_name, sku, '(isimsiz)'), COALESCE(status, 'acik'),
         found_at, (CURRENT_DATE - found_at)
    FROM "cfo_dead_stock_finding"
   WHERE COALESCE(status, 'acik') NOT IN ('kapandi', 'gecersiz')
UNION ALL
  SELECT 'soru', id, left(question, 70), status,
         ("askedAt")::date, (CURRENT_DATE - ("askedAt")::date)
    FROM "cfo_question" WHERE status = 'ACIK'
UNION ALL
  SELECT 'bayat_not', id, title, 'gozden_gecir',
         ("reviewBy")::date, (CURRENT_DATE - ("reviewBy")::date)
    FROM "cfo_note"
   WHERE "archivedAt" IS NULL AND "reviewBy" IS NOT NULL AND "reviewBy" < now();

CREATE OR REPLACE VIEW "cfo_gecikmis_karar" AS
SELECT * FROM "cfo_bekleyen_karar" WHERE bekleme_gun >= 3
ORDER BY bekleme_gun DESC, tur;

COMMENT ON VIEW "cfo_gecikmis_karar" IS
  '3 gündür karara bağlanmamış her şey. Sabah raporunda boş olmak zorunda.';
