export const COMPANY_SETTINGS = {
  companyName: "Soylu Elektronik",
  tagline: "Elektronik ve Güvenlik Sistemleri",
  salesContact: "Satış Departmanı",
  website: "soyluelektronik.com",
  email: "info@soyluelektronik.com",
  phone: "08503077397",
  address: "Perpa Ticaret Merkezi A Blok No:758 Şişli/İstanbul",
  taxOffice: "Belirlenecek",
  taxNumber: "Belirlenecek",
  paymentTerms: "Ödeme ve teslimat koşulları teklif onayı sonrasında netleştirilir.",
  deliveryTerms: "Teslim süresi stok ve tedarik durumuna göre ayrıca teyit edilir.",
  warrantyTerms: "Ürün garantisi üretici firma şartlarına tabidir.",
  logoUrl: "",
  brandColor: "#F97316",
  accentColor: "#F97316",
} as const;
