// Forecast consumer audit (PR2). One row per call site that computes or consumes a monthly demand signal. Rendered on /admin/forecast-v2,
// mirrored in docs/FORECAST-V2.md and enforced by __tests__/forecast-consumers.test.ts (MIGRATE_V2 files must gate on the flag through
// lib/forecast/consumer; KEEP_LEGACY / DEPRECATE files must not import it).
export type ConsumerDecision = "MIGRATE_V2" | "KEEP_LEGACY" | "DEPRECATE";
export interface ConsumerAuditRow { id: string; file: string; legacy: string; drives: string; decision: ConsumerDecision; v2: string }

export const FORECAST_CONSUMERS: ConsumerAuditRow[] = [
  { id: "importer-view", file: "app/api/products/importer-view/route.ts", decision: "MIGRATE_V2",
    legacy: "max(forecastMonthlySales(UNION ALL 3 tablo, ay kovası, max/mevsim), onlineSalesPotential)",
    drives: "stok günü, sağlık skoru, karar etiketi, bütçe dağıtımı (allocateBudget) → sipariş ön doldurma",
    v2: "efektif = FULL dereceli V2; manuel yalnız karşılaştırma; eski değer forecastV2.legacy* alanında" },
  { id: "importer-view-client", file: "components/products/importer-view-client.tsx", decision: "MIGRATE_V2",
    legacy: "satır içi düzenlemede max(tahmin, manuel) yeniden hesap; stoksuz ürüne ömür boyu hızla adet ipucu",
    drives: "bütçe dağıtımı, karar etiketi, sipariş linki", v2: "V2 açıkken manuel düzenleme talebi değiştirmez; eski kaynaklı ömür boyu adet ipucu gizlenir" },
  { id: "sermaye-saglik", file: "app/(app)/admin/sermaye-saglik/page.tsx", decision: "MIGRATE_V2",
    legacy: "max(forecastMonthlySales(UNION ALL), onlineSalesPotential)", drives: "aylık kâr, stok günü, acil sayısı, yıldızlar (gösterim)",
    v2: "efektif = FULL dereceli V2; t30g/prevT30g gösterimi eski kalır" },
  { id: "dashboard-capital-snapshot", file: "services/dashboard-service.ts", decision: "MIGRATE_V2",
    legacy: "max(Trendyol 30g iptal/cancel hariç, onlineSalesPotential)", drives: "sermaye skoru, acil sipariş sayısı, yıldız sayısı (gösterim)",
    v2: "efektif = FULL dereceli V2" },
  { id: "smart-recommendations", file: "lib/smart-recommendations.ts", decision: "MIGRATE_V2",
    legacy: "max(Trendyol 30g, onlineSalesPotential)", drives: "yıldız ürün önerileri (gösterim)", v2: "efektif = FULL dereceli V2" },
  { id: "import-cockpit", file: "app/(app)/admin/import-cockpit/page.tsx", decision: "MIGRATE_V2",
    legacy: "max(Trendyol 30g Delivered × (1 − iade oranı), online) + toptan + bayi; STOKSUZ_AL için ömür boyu hız yedeği",
    drives: "AL/BEKLE/ALMA sinyali, 90 gün önerilen adet → sipariş ön doldurma",
    v2: "talep = FULL dereceli V2 (manuel kanallar yok); STOKSUZ_AL sinyali kalır, eski kaynaklı adet önerilmez" },
  { id: "capital", file: "app/(app)/admin/capital/page.tsx", decision: "MIGRATE_V2",
    legacy: "max(Trendyol 30g, online) + toptan + bayi → calculateSalesPotential / calculateCapitalAllocation",
    drives: "yatırım skoru, sermaye dağıtım özeti", v2: "online = FULL dereceli V2; manuel toptan/bayi sermaye hesabına girmez (lib değişmedi)" },
  { id: "purchase-order-prefill", file: "app/(app)/admin/purchase-orders/new/page.tsx", decision: "MIGRATE_V2",
    legacy: "online + toptan + bayi manuel potansiyel; öneri = 2 × aylık − stok", drives: "taslak sipariş formu ön doldurma (kayıt kullanıcı + borç kapısıyla)",
    v2: "aylık = FULL dereceli V2; 0 ise yalnız minimum stok kuralı" },
  { id: "product-detail", file: "app/(app)/products/[id]/page.tsx", decision: "MIGRATE_V2",
    legacy: "ithalat kararı monthlyUnits = manuel potansiyel toplamı", drives: "ithalat kararı rozeti ve senaryo kâr/sermaye gösterimi",
    v2: "monthlyUnits = FULL dereceli V2; satış potansiyeli kartı manuel kalır (KEEP)" },
  { id: "import-snapshot", file: "lib/actions/import-snapshot-actions.ts", decision: "MIGRATE_V2",
    legacy: "monthlyUnits = manuel potansiyel toplamı", drives: "ImportDecisionSnapshot kaydı (karar/puan büyüklükten bağımsız, yalnız > 0 kapısı)",
    v2: "monthlyUnits = FULL dereceli V2; eski kayıtlar değişmez" },
  { id: "sales-potential-card", file: "lib/sales-potential.ts", decision: "KEEP_LEGACY",
    legacy: "manuel potansiyellerden projeksiyon (saf motor)", drives: "ürün sayfası satış potansiyeli kartı; capital sayfası girdisi çağırandan gelir",
    v2: "motor değişmedi; girdiyi çağıran belirler" },
  { id: "capital-allocation-engine", file: "lib/capital-allocation.ts", decision: "KEEP_LEGACY",
    legacy: "saf motor (talep çağırandan)", drives: "capital sayfası", v2: "değişmedi (Capital Allocation V2 kapsam dışı)" },
  { id: "import-decision-engine", file: "lib/import-decision.ts", decision: "KEEP_LEGACY",
    legacy: "saf motor (monthlyUnits çağırandan)", drives: "ürün sayfası, snapshot, kokpit iniş maliyeti", v2: "değişmedi" },
  { id: "stock-health", file: "app/(app)/admin/stock-health/page.tsx", decision: "KEEP_LEGACY",
    legacy: "Trendyol 30g gözlenen hız (tahmin değil, manuel yok)", drives: "kapsam günü gösterimi", v2: "gözlem metriği; ayrı PR'de kanoniğe geçebilir" },
  { id: "marketplace-profit", file: "app/(app)/marketplace/profit/page.tsx", decision: "KEEP_LEGACY",
    legacy: "onlineSalesPotential = 0 → 'yüksek stok düşük satış' işareti", drives: "gösterim", v2: "manuel veri bütünlüğü göstergesi" },
  { id: "cfo-agent", file: "lib/cfo-agent/snapshot.ts", decision: "KEEP_LEGACY",
    legacy: "min(kanonik satış/30, XML ihtiyatlı hız) — asla max", drives: "AI CFO anomali/iş planı (borç kapısı dahil)",
    v2: "zaten ihtiyatlı ve kanonik; AI CFO / Decision Memory kapsam dışı" },
  { id: "cfo-import-planner", file: "lib/cfo-agent/import-planner.ts", decision: "KEEP_LEGACY",
    legacy: "cfo_order_line.monthly_sales (elle girilmiş saklı değer)", drives: "ithalat planı kapsam soruları",
    v2: "saklı satırlar değiştirilmez; gölge raporu V2 ile farkı gösterir" },
  { id: "procurement-engine", file: "lib/procurement.ts", decision: "DEPRECATE",
    legacy: "manuel toplam / 30 ile aciliyet", drives: "hiçbir çağıran yok (ölü kod)", v2: "kaldırma ayrı temizlik PR'ı" },
  { id: "executive-dead-selects", file: "app/(app)/admin/executive/page.tsx", decision: "DEPRECATE",
    legacy: "potansiyel alanları seçiliyor ama kullanılmıyor", drives: "yok", v2: "kaldırma ayrı temizlik PR'ı" },
  { id: "sales-forecast-legacy", file: "lib/sales-forecast.ts", decision: "KEEP_LEGACY",
    legacy: "forecastMonthlySales + effectiveMonthlyUnits (max)", drives: "bayrak kapalıyken importer-view ve sermaye-sağlık; bayrak açıkken yalnız karşılaştırma",
    v2: "bayrak kalıcı açılıp gölge onaylanınca DEPRECATE adayı" },
];
