// ÜRETİLMİŞ DOSYA — elle düzenlemeyin. Kaynak: lib/cfo-agent/rule-cards.md (npm run gen:handbook).
// SCHEDULED_CFO rule card'ları: el kitabından birebir alıntılar; bir anomali yalnız kendi kartını alır.

export const RULE_CARDS_VERSION = "v33-cards-7";

export const RULE_CARDS = {
  "STOCKOUT": "🔴 **CFO ÖZ ELEŞTİRİSİ 03.10 — MD-3003B1 birim kârı yanlış raporlandı: 160,32 ₺ değil\n123,55 ₺.** Doğrusu: komisyon %16,83 (28 tek kalemli kayıt) → taban 627,57/(1−0,1683) =\n**754,00 ₺**; gerçekleşen fiyat 903,23 ₺ → **birim kâr 123,55 ₺**. Stoksuzluk maliyeti\n**658–914 ₺/gün** (5,33–7,40 adet/gün × 123,55).\n\n- 🔴 **STOK DÜŞÜŞÜ SATIŞ DEĞİLDİR** (§4C, §9).\n- **Kukla stok gerçek envanter değildir:** {500, 998, 999, 1000, 9999, 10000}.\n\n- 🔴 **Gümrük ödemeleri NAKİT zorunludur.** Gümrükte **taksitlendirme ve teminat\n  mektubuyla mal çekimi YOKTUR** (gümrük müşaviri 30.08.2026 kesin ret).\n- 🔴 **Net nakit pozisyonu −3.000.000 ₺ altına inemez.**\n- 🔴 **Yurtdışı sipariş YALNIZCA NAKİT ile verilir.** Nakit değildir: KMH · kart limiti ·\n  nakit avans · şahsi hesaplar · tahsil edilmemiş hakediş.",
  "DEAD_STOCK": "🔴 **MERDİVENİN 1–6. BASAMAĞI TÜKENDİYSE 7. BASAMAK SAYIYLA RAPORLANIR (v31).**\n`cfo_kart_karari()` \"asgariye çekilecek 0 kalem · kaldıraç YETERSİZ\" dediğinde geriye\n**ölü stok tasfiyesi** kalır ve bu, raporun 1. maddesidir. Ölçülecek üç sayı:\n(a) KIRMIZI ölü stokta bağlı sermaye, (b) en büyük kalemin payı, (c) maliyetin %50'sine\ntasfiyenin açığa oranı. *04.10: KIRMIZI ölü stok 2.009.195 ₺ · AL-CAM03 tek başına\n940.900 ₺ = %47 · %50'ye tasfiye 470.450 ₺ = açığın %32'si.*\n\n> 🔴 **BİR SET İLANI, BİLEŞENİN ÖLÜ STOĞUNU ERİTME ARACI OLARAK SAYILMADAN ÖNCE\n> SATTIĞI ADET ÖLÇÜLÜR** (v31). *04.10: 8'li kamera seti 120 günde 2 adet sattı =\n> 16 kamera; AL-CAM03'ün 1.940 adedi için ~40 yıl.*\n\n- **PARA MALİYETİ MERDİVENİ (aylık, 14.09 akşamı):** Ziraat Kredi 2 **%2,83** <\n  Ziraat KGF **%3,08** < **taksitli nakit avans ~%3,74 efektif** ≈ Fibabanka **%3,76**\n  < Ziraat KMH **%4,08** < YKB ticari **%4,18** < **Enpara kart alışveriş %4,25\n  (ÖLÇÜLDÜ)** ≈ Enpara KMH %4,25 < Garanti ticari **%4,31** < YKB KMH **%4,50** <\n  diğer kartlar **%4,50 (TAHMİNİ)** << **şahsi KMH ~%7 efektif**.",
  "PRICE_FLOOR": "> **Hiçbir ürün 200,00–243,70 ₺ veya 350,00–365,50 ₺ aralığında fiyatlanmaz.**\n> 199 yap ya da 250 üstüne çık.\n\n🔴 **Taban fiyat bir bant eşiğini aşıyorsa TABAN YENİDEN HESAPLANIR.**\n\n```\nTABAN = (birim maliyet + kargo [cfo_kargo_tarife] + ambalaj + iade 13,36\n         + işlem 12,29 + hizmet/ceza payı 10,00) / (1 − komisyon)\n```\n**Ambalaj:** ≤0,5 kg → 10 ₺ · üstü → 18,74 ₺.\n\n🔴 **Bu 8 kanalda taban fiyat \"TAHMİNİ\" olarak bile yazılamaz — YOKTUR.** O kanallarda\nverilen her fiyat kararı (indirim, kampanya, yeni listeleme) ölçümsüzdür ve raporda\nböyle etiketlenir. **180 günlük ciro payı: 1.076.152 ₺.**\n\nKayıt sayısı **10'un altındaysa** kanal ortalaması kullanılır ve taban **TAHMİNİ**\netiketlenir.\n\n> Bir fiyat indiriminin işe yarayıp yaramadığı **sipariş adedinin artmasıyla** değil,\n> yeni fiyatın **taban fiyata olan mesafesiyle** ölçülür.\n\nFiyat değişikliği **Alperen onayı** ister.",
  "CASH_SHORTFALL": "**2. 🔴 Dip TEK SAYI DEĞİL BANT olarak raporlanır:**\n```\nALT UÇ  = defter (panel rakamları, muhafazakâr)\nÜST UÇ  = defter + olgunlaşma payı (TAHMİNİ, açıkça etiketli)\n```\n\n**2c. 🔴 OLGUNLAŞMA BANDI, DİP GÜNÜ 35 GÜNDEN UZAKSA O DİBİ DÜZELTMEZ — 18.09.**\nPanel yalnızca ~35 gün ileriyi gösterir. Dip günü bundan uzaktaysa o tarihe kadarki\nhakediş akışının tamamı defterde yoktur; **iki ayrı dip ayrı raporlanır.**\n\n**KURAL: panel ufkunun ötesi ya MODELLENİR (§2F-16) ya da o aralık için dip \"ölçülemez\"\nyazılır. Sıfır giriş varsayılarak hesaplanmış bir dip raporlanamaz.**\n\n**Net nakit pozisyonu −3.000.000 ₺'nin altına inemez.**\n\n- 🔴 **Banka ekranındaki \"kullanılabilir bakiye\" NAKİT DEĞİLDİR.**\n- 🔴 **Bayat bakiye, kullanılmış KMH'yi GÖRÜNMEZ yapar.**\n- 🔴 **Vadesi geçmiş tahsil edilmemiş alacak GELECEK GİRİŞ SAYILMAZ.**\n  🔴 **Ve İLERİ TARİHE DE ALINMAZ** (v27).",
  "CAPITAL_ALLOCATION": "Motor `YETERSIZ` derse kaldıraç merdiveni: kısmi çekim → antrepoda bekletme → Trendyol\nerken ödeme → sabit gider kısma → borç yapılandırma → ölü stok tasfiyesi → şahsi hesaplar.\n\n🔴 **Motor `YETERSIZ` dediğinde, merdivenin 1. basamağı SAYIYLA raporlanır.**\n\"Kısmi çekim yapılmalı\" bir cümle değil bir **orandır**: `cfo_gumruk_dilim()`\nçıktısındaki `CEKILEBILIR ORAN (%)`. Bu alan `null` dönüyorsa fonksiyon doğru günü\nbulamıyordur — **önce onu düzelt, sonra raporla** (v27).\n\n- 🔴 **Şahsi KMH son çaredir — iki kere pahalıdır** (KKDF %15 + BSMV %5, gider\n  gösterilemez → ~1,6–1,8× pahalı).\n\n- 🔴 **TAKSİTLİ NAKİT AVANS, ŞAHSİ KMH'DEN ÖNCE GELİR.**",
  "DEBT_GATE": "- 🔴 **BORÇ KAPATMA SIRASI, FAİZ ORANINA DEĞİL AYLIK ZORUNLU NAKİT ÇIKIŞINA GÖRE KURULUR** (v29).\n  Oranlar birbirine yakınsa ayıran şey **asgari oranıdır**. Sıra (03.10, H12): Garanti Alp\n  5.000 ₺ (13.10'da kapatılır) → **Akbank Alp 344.335,37 ₺** (15.10 konteyneri geçildikten\n  sonra ilk serbest nakit) → sonra şirket kartları: Ziraat 746.276 > Garanti ana 618.576 >\n  Enpara 523.978 > Garanti Fatih 127.852. **Şahsi kartlar şirket kartlarından önce gelir**:\n  faizi gider yazılamaz (~1,33× pahalı) ve borç Alperen'in kredi notunu tutar.\n\n- 🔴 **KART ASGARİSİ BİR KÖPRÜDÜR, POLİTİKA DEĞİLDİR.** *11.09 ÖLÇÜLDÜ: ayda 200.000 ₺\n  yeni kart harcaması. Kart borcu 2.366.017 ₺ (03.10), aylık faiz %4,50 ≈ 106.471 ₺.*\n\n- 🔴 **Gümrük ödemeleri NAKİT zorunludur.** Gümrükte **taksitlendirme ve teminat\n  mektubuyla mal çekimi YOKTUR** (gümrük müşaviri 30.08.2026 kesin ret).\n\n- 🔴 **Yurtdışı sipariş YALNIZCA NAKİT ile verilir.** Nakit değildir: KMH · kart limiti ·\n  nakit avans · şahsi hesaplar · tahsil edilmemiş hakediş.",
  "DATA_QUALITY": "**Genel kural:** bir sayıyı bölmeden önce payın ve paydanın **aynı taneye** ait\nolduğunu doğrula.\n\n> 🔴 **BİR SENKRONUN GÜNCEL VERİ GETİRMEMESİ, ÇALIŞMAMASIYLA AYNI ŞEY DEĞİLDİR.**\n> Teşhis \"senkron çalışıyor mu\" değil **\"getirdiği kayıtların tarihi ne\"** sorusuyla konur.\n\n- **Rakam uydurma.** Her veri: Kesin / Tahmini / Eski / Teyit edilmeli.\n\n- 🔴 **BEYAN KANIT DEĞİLDİR — beyanın bırakması gereken İZ aranır** (§4E).\n- 🔴 **TEK BİR SATIŞ, VEYA AYLAR ÖNCESİNE AİT BİR KAYIT, GÜNCEL FİYAT DEĞİLDİR.**"
} as const;

export type RuleCardId = keyof typeof RULE_CARDS;
