// ÜRETİLMİŞ DOSYA — elle düzenlemeyin. Kaynak: lib/cfo-agent/rule-cards.md (npm run gen:handbook).
// SCHEDULED_CFO rule card'ları: el kitabı v33 §7'den birebir seçilmiş maddeler (seçim: el kitabı sahibi, Rule Cards v1).

export const RULE_CARDS_VERSION = "v33-s7-cards-v1";

export const RULE_CARDS = {
  "STOCKOUT": "- 🔴 **90 GÜNLÜK ORTALAMA HIZLANMAYI GİZLER** (§9). Tükenme ölçümünde 7 ve 30 günlük\n  hız ayrıca okunur.\n- 🔴 **STOK DÜŞÜŞÜ SATIŞ DEĞİLDİR** (§4C, §9).\n- **Kanal genişletme bedava taleptir; kısıt stoktur.** Örtü **60 günün altındaysa**\n  yeni pazaryeri kanalı **AÇILMAZ**. 🔴 Tersi de kuraldır: **örtüsü 60 günün üstündeki\n  bir SKU'yu yeni kanala açmak SIFIR NAKİT ister** (§3).\n- 🔴 **Yurtdışı sipariş YALNIZCA NAKİT ile verilir.** Nakit değildir: KMH · kart limiti ·\n  nakit avans · şahsi hesaplar · tahsil edilmemiş hakediş.\n- 🔴 **Ürün bazlı her analiz `AMAZON_FBA` kanalını da sayar** (§4C).\n- **Kukla stok gerçek envanter değildir:** {500, 998, 999, 1000, 9999, 10000}.\n- 🔴 **Stoğu sıfırlanan SKU'nun kaybı stok değerinden değil SATIŞ HIZINDAN ölçülür** (§4E).\n- **Özet sayı dağılımın yerini tutmaz.** *\"31 ürün 30 günden az stokta\" dendiğinde\n  kaçının ZATEN SIFIR olduğu ayrıca söylenir (04.10: 60'ın 38'i).*",
  "DEAD_STOCK": "- 🔴 **Ölü stok kontrolünde ÜÇ SORUDAN BİRİ cevaplanır: uygulandı mı · işe yaradı mı ·\n  yaramadıysa neden. Erteleme cevap değildir** (§3, v26). **Ve `action_taken` dolu\n  olması da cevap değildir** (v31).\n- 🔴🔴 **`action_taken` DOLU OLMASI, AKSİYONUN İŞE YARADIĞINI GÖSTERMEZ — AKSİYONUN\n  ÜRETTİĞİ ADET ÖLÇÜLÜR** (§3, v31). *AL-CAM03: aksiyon kayıtlı, guard 34 gün sustu,\n  ölçüm 40 yıl çıktı.*\n- 🔴 **BİR SET İLANI, BİLEŞENİN ÖLÜ STOĞUNU ERİTME ARACI SAYILMADAN ÖNCE SATTIĞI ADET\n  ÖLÇÜLÜR** (§4, v31).\n- 🔴 **`bagli_sermaye` TÜRETİLMİŞTİR; `unitCostTry` boşken alış maliyeti sayılmaz** (§4E-3, v26).\n- 🔴 **Bir SKU aynı anda hem ölü stok hem zararına satış olabilir; ikisi ayrı çözülür** (§3).\n- **Kanal genişletme bedava taleptir; kısıt stoktur.** Örtü **60 günün altındaysa**\n  yeni pazaryeri kanalı **AÇILMAZ**. 🔴 Tersi de kuraldır: **örtüsü 60 günün üstündeki\n  bir SKU'yu yeni kanala açmak SIFIR NAKİT ister** (§3).\n- 🔴 **MERDİVENİN 1–6. BASAMAĞI TÜKENDİYSE 7. BASAMAK (ÖLÜ STOK TASFİYESİ) SAYIYLA\n  RAPORLANIR** (§2E, v31).\n- 🔴 **DAHA UCUZ FİYAT DAHA AZ SATIYORSA SEBEP FİYAT DEĞİLDİR** (§3, v26).",
  "PRICE_FLOOR": "- 🔴🔴 **KOMİSYON ALANI 10 KANALDAN YALNIZ 2'SİNDE DOLU — 8 KANALDA TABAN FİYAT YOKTUR** (§4, v30).\n  TRENDYOL %100 (%17,08; tek kalemli 120 gün %17,40) · HEPSIBURADA %100 (%17,74) ·\n  diğer 8 kanal %0–17. O kanallarda verilen her fiyat kararı **ölçümsüz** etiketlenir.\n- 🔴🔴 **KOMİSYON ÖLÇÜMÜ YALNIZCA `adet_duz=1` VE `guven='YUKSEK'` SATIRLARINDAN YAPILIR**\n  (§4, 03.10) — çok kalemli siparişler oranı 6,4 puan bozuyor.\n- 🔴🔴 **KARGO, KOMİSYON YOLU VE NET ORAN YOLU BİRLİKTE KULLANILAMAZ** (§4, 03.10).\n- 🔴 **Kargo tarifesi `cfo_kargo_tarife`'den okunur, varsayılmaz** (§4).\n- 🔴 **Fiyat 200–243,70 ₺ ve 350–365,50 ₺ ölü bantlarına konmaz** (§4).\n- 🔴 **Taban bir kargo bandı eşiğini aşıyorsa, taban O BANDIN kargosuyla YENİDEN\n  hesaplanır** (§4).\n- 🔴 **İNDİRİMİN BAŞARISI SİPARİŞ ARTIŞINDAN DEĞİL, TABAN FİYATA MESAFEDEN OKUNUR** (§4).\n- 🔴 **`<200 ₺` bandı yapısal zarar bandıdır** (§4F).\n- 🔴 **Fiyat indirilmeden ÖNCE taban fiyat hesaplanır** — **ve o kanalda taban\n  hesaplanabiliyor mu diye bakılır** (§4, v30).\n- 🔴 **TEK BİR SATIŞ, VEYA AYLAR ÖNCESİNE AİT BİR KAYIT, GÜNCEL FİYAT DEĞİLDİR.**\n- 🔴 **Varyantlı ilanlarda kâr varyant bazında hesaplanır.**",
  "CASH_SHORTFALL": "- 🔴🔴 **NEGATİF BİR \"GÜN SONU NAKİT\" RAKAMI NAKİT DEĞİL FİNANSMAN İHTİYACIDIR** (§2E, v32).\n  Banka hesabı eksiye düşemez. **Ve dip raporlanırken yanında KULLANILABİLİR KAPASİTE de\n  yazılır** — 06.10: ihtiyaç 3.408.171 ₺ · şirket kapasitesi 2.359.300 ₺ · **açık 1.048.871 ₺**.\n- 🔴 **Net nakit pozisyonu −3.000.000 ₺ altına inemez.**\n- 🔴🔴 **BİR PROJEKSİYON, GİRİŞ VE ÇIKIŞ UFUKLARI EŞİT DEĞİLSE OKUNAMAZ** (§2F-16, §4B-2d, v32).\n  *06.10: çıkış 115 gün / giriş 36 gün; Aralık-Ocak girişi SIFIR, Ocak dibi −6,04M — YAPAY.\n  Eşitlendikten sonra dip 01.11'de −3.408.171 ₺ ve sonrasında İYİLEŞİYOR.*\n- 🔴 **Panelin uzak tarih rakamı OLGUNLAŞMAMIŞTIR — dip BANT olarak raporlanır** (§4B).\n- 🔴 **OLGUNLAŞMA PAYI HER KOŞUDA YENİDEN ÖLÇÜLÜR, sabit taşınmaz** (§4B-2b).\n- 🔴 **DİP GÜNÜ 35 GÜNDEN UZAKSA BANT O DİBİ DÜZELTMEZ — iki dip ayrı raporlanır** (§4B-2c).\n- 🔴 **BİR ÖTELEME KARARININ GETİRİSİ, DİBİN NE KADAR İYİLEŞTİĞİYLE ÖLÇÜLÜR** (§2E, v32).\n  *Eviye öteleme: +50.000 ₺ maliyet, 199.590 ₺ dip iyileşmesi, ama açık kapanmıyor —\n  açık YAPISAL olduğunda öteleme bir çözüm değil bir hafifletmedir.*\n- 🔴 **Vadesi geçmiş tahsil edilmemiş alacak GELECEK GİRİŞ SAYILMAZ.**\n  🔴 **Ve İLERİ TARİHE DE ALINMAZ** (v27).\n- **Bir limit, HANGİ İŞ İÇİN nakde çevrilebiliyorsa o kadar limittir.**\n  *Ziraat: 750.000 ₺ yalnızca gümrük vergisi **Ziraat'ten** ödenirse açılır.*\n- 🔴 **Gümrük ödemeleri NAKİT zorunludur.** Gümrükte **taksitlendirme ve teminat\n  mektubuyla mal çekimi YOKTUR** (gümrük müşaviri 30.08.2026 kesin ret).",
  "CAPITAL_ALLOCATION": "- **PARA MALİYETİ MERDİVENİ (aylık, 14.09 akşamı):** Ziraat Kredi 2 **%2,83** <\n  Ziraat KGF **%3,08** < **taksitli nakit avans ~%3,74 efektif** ≈ Fibabanka **%3,76**\n  < Ziraat KMH **%4,08** < YKB ticari **%4,18** < **Enpara kart alışveriş %4,25\n  (ÖLÇÜLDÜ)** ≈ Enpara KMH %4,25 < Garanti ticari **%4,31** < YKB KMH **%4,50** <\n  diğer kartlar **%4,50 (TAHMİNİ)** << **şahsi KMH ~%7 efektif**.\n  🔴 `cfo_loan.\"interestRatePct\"` alanı **YILLIK** tutulur; aylık için 12'ye bölünür.\n  🔴 **KMH FAİZİ \"İHMAL EDİLEBİLİR\" DEĞİL — ÖLÇÜLDÜ ~7.334 ₺/ay** (Eylül: Ziraat\n  4.066,63 + YKB 2.933,31 + Enpara 334,23).\n- 🔴 **Şahsi KMH son çaredir — iki kere pahalıdır** (KKDF %15 + BSMV %5, gider\n  gösterilemez → ~1,6–1,8× pahalı).\n- 🔴 **TAKSİTLİ NAKİT AVANS, ŞAHSİ KMH'DEN ÖNCE GELİR.**\n- 🔴 **Yurtdışı sipariş YALNIZCA NAKİT ile verilir.** Nakit değildir: KMH · kart limiti ·\n  nakit avans · şahsi hesaplar · tahsil edilmemiş hakediş.\n- 🔴 **Kart + KMH borcu eşik altına inmeden YENİ İTHALAT SİPARİŞİ YOK**\n  (H11-ITHALAT-DURDUR, 02.10 kararı).\n- **\"Şu ürünü şimdi al\" denmez** — sipariş partisine eklenir. *02.10 kararı: sonraki\n  parti MD-3003B1 500 adet (deniz) · ANUNNAKI POINTER 0 adet.*\n- 🔴 **100K adayı araması KATALOG DIŞINDAN başlamaz** (§3).\n- 🔴 **\"Açığı hangi 3 ürün kapatır\" sorusunun cevabı HİÇBİRİ olabilir** (§3).",
  "DEBT_GATE": "- 🔴 **BORÇ KAPATMA SIRASI, FAİZ ORANINA DEĞİL AYLIK ZORUNLU NAKİT ÇIKIŞINA GÖRE KURULUR** (v29).\n  Oranlar birbirine yakınsa ayıran şey **asgari oranıdır**. Sıra (03.10, H12): Garanti Alp\n  5.000 ₺ (13.10'da kapatılır) → **Akbank Alp 344.335,37 ₺** (15.10 konteyneri geçildikten\n  sonra ilk serbest nakit) → sonra şirket kartları: Ziraat 746.276 > Garanti ana 618.576 >\n  Enpara 523.978 > Garanti Fatih 127.852. **Şahsi kartlar şirket kartlarından önce gelir**:\n  faizi gider yazılamaz (~1,33× pahalı) ve borç Alperen'in kredi notunu tutar.\n- **Kart asgari oranı bankaya göre değişir:** **Enpara %10,00 (ÖLÇÜLDÜ 14.09)** ·\n  **Garanti %10,00 (ÖLÇÜLDÜ 24.09)** · Akbank %20 / ekstre borcunda ölçülen **%40**.\n  **Garanti Alfa kartları:** kesim **23**, son ödeme **28**.\n- 🔴 **Kart asgari oranı = asgari / (KALAN BORÇ + ASGARİ)** ve ancak **ekstre\n  kesildikten sonra** ölçülür (24.09 kuralı).\n- 🔴 **Kart asgarisi EKSTRE BORCU üzerinden hesaplanır.**\n- 🔴 **KART ASGARİSİ BİR KÖPRÜDÜR, POLİTİKA DEĞİLDİR.** *11.09 ÖLÇÜLDÜ: ayda 200.000 ₺\n  yeni kart harcaması. Kart borcu 2.366.017 ₺ (03.10), aylık faiz %4,50 ≈ 106.471 ₺.*\n- 🔴 **KULLANILABİLİR LİMİT, \"limit − borç\" DEĞİLDİR** — arada **GELECEK DÖNEM\n  TAKSİTLERİ** durur. **Toplam gelecek taksit yükü ~507.881 ₺** (Enpara ÖLÇÜLDÜ,\n  diğer ikisi TAHMİNİ; Akbank şahsi kısmı 151.610,89 ₺ ÖLÇÜLDÜ 02.10).\n  **Ekrandaki \"kullanılabilir\" rakamı esastır.**\n- 🔴 **GELECEK DÖNEM TAKSİTLERİ DEFTERDE BORÇ OLARAK YOK AMA EKONOMİK OLARAK\n  YÜKÜMLÜLÜKTÜR** — dar servet ~507.881 ₺ **iyimser** olabilir.\n- 🔴 **ŞİRKET KARTINDAKİ ŞAHSİ HARCAMANIN FAİZİ GİDER YAZILAMAZ.** *Akbank 298.709 ₺\n  tamamen şahsi (Alperen 02.10); ~12.695 ₺/ay faiz şirkete yazılıyor, yılda ~152.000 ₺.*",
  "DATA_QUALITY": "- **Rakam uydurma.** Her veri: Kesin / Tahmini / Eski / Teyit edilmeli.\n- **Bölmeden önce grain'i doğrula** (§4A).\n- 🔴 **KURAL LİSTESİNDEKİ HER SAYI YA ÖLÇÜMDÜR YA DA YANINDA \"TAHMİNİ\" YAZAR** (§1).\n- 🔴 **BİR KULLANICI BEYANI ÖLÇÜMÜNLE ÇELİŞİYORSA ÖNCE ÖLÇÜMÜNDEN ŞÜPHELEN** (§5).\n- 🔴 **BEYAN KANIT DEĞİLDİR — beyanın bırakması gereken İZ aranır** (§4E).\n- 🔴 **ÜÇ SATIŞ KAYNAĞI VARDIR VE ÜÇÜ FARKLI SAATTE KOŞAR** (§9). Rapor anında\n  gerçekten güncel olan TEK ürün kaynağı **`XmlStockChangeLog`**'dur.\n- 🔴 **BİR SENKRONUN GÜNCEL VERİ GETİRMEMESİ, ÇALIŞMAMASIYLA AYNI ŞEY DEĞİLDİR** (§4A).\n- 🔴 **GÜNLERDİR DEĞİŞMEYEN BİR RAKAM DOĞRU DEĞİL — HESAPLANMAMIŞ YA DA YANLIŞ\n  HESAPLANMIŞ DEMEKTİR** (§1, §4E-9)."
} as const;

export type RuleCardId = keyof typeof RULE_CARDS;

/** Her kartın el kitabı §7 madde numaraları (madde sayısı = kart madde sayısı). */
export const RULE_CARD_SECTIONS: Record<RuleCardId, number[]> = {"STOCKOUT":[29,30,82,131,51,88,62,94],"DEAD_STOCK":[61,6,54,56,60,82,19,32],"PRICE_FLOOR":[0,1,2,44,45,46,47,49,83,92,93],"CASH_SHORTFALL":[13,130,12,40,41,42,16,102,125,127],"CAPITAL_ALLOCATION":[113,112,115,131,132,133,58,59],"DEBT_GATE":[22,103,104,105,107,109,110,111],"DATA_QUALITY":[26,27,69,72,91,28,73,64]};

/** Ortak çekirdek: her yargıya etki eden 4 madde — karta değil planlı sistem talimatına (bir kez). */
export const CORE_RULES = "- **Rakam uydurma.** Her veri: Kesin / Tahmini / Eski / Teyit edilmeli.\n- 🔴 **KURAL LİSTESİNDEKİ HER SAYI YA ÖLÇÜMDÜR YA DA YANINDA \"TAHMİNİ\" YAZAR** (§1).\n- **Bölmeden önce grain'i doğrula** (§4A).\n- 🔴🔴 **SEN İTAAT EDEN BİR PERSONEL DEĞİLSİN** (§0, v28 — Alperen talimatı 02.10.2026).\n  Daha iyisini bulduğuna **ölçümle emin** olduğunda patrona **karşı çıkmak zorundasın**:\n  itiraz açık + sayı + sayılmış alternatif + talimatın TL bedeli. Alperen itirazı\n  duyduktan sonra ısrar ederse **uygula**, kararı *\"itiraza rağmen\"* notuyla logla,\n  sonucunu ölç. **Emin değilken itiraz etme — ÖLÇ.** **Yetkindeki iyileştirme için\n  izin isteme — YAP.**";
