import type { CfoNotebook } from "./notebook";
export const SCHEMA_VERSION = "2";
export const CALCULATION_VERSION = "alfas-gross-v7";
export type Basis = "gross_incl_vat" | "net_ex_vat";
export type Metric = { value: number | null; estimated: boolean; basis: Basis; reason?: string };
export type Severity = "info" | "warning" | "critical";
export type Category = "margin" | "inventory" | "sales" | "cash" | "pricing" | "procurement" | "marketing" | "data_quality";
export type Evidence = { id: string; source: string; query: string; value: number | string | null; unit: string; asOf: string; measured: boolean };
export type Impact = { value: number; formula: string; inputs: Record<string, number>; basis: Basis; estimated: boolean };
export type SourceWatermark = { source: string; orderDate: string | null; syncedAt: string | null; batchDays: number; coverageDays: number; stale: boolean };
export type Profitability = {
  grossRevenue: Metric; revenueExVat: Metric; vat: Metric; refunds: Metric;
  productCost: Metric; commission: Metric; shipping: Metric; advertising: Metric;
  otherVariableCosts: Metric; contributionProfit: Metric; contributionMargin: Metric;
};
export type SalesPeriod = { grossRevenue: Metric; orders: number | null; aov: Metric; complete: boolean };
export type Comparison = { entity: string; current: Metric; previous: Metric; complete: boolean; sourceFresh: boolean; period: string };
export type ProductSignal = {
  sku: string; channel: string; isSet: boolean; trusted: boolean; sourceFresh: boolean;
  financialSourceFresh?: boolean; inventorySourceFresh?: boolean; catalogSku?: string;
  cost: Metric; avgPrice: Metric; commissionRate: Metric; commissionSamples: number; priceFloor: Metric;
  zeroCommissionFloor: Metric; unitProfit: Metric; previousUnitProfit: Metric;
  contribution: Metric; previousMargin: Metric; margin: Metric;
  salesUnits30: Metric; xmlUnits30: Metric; salesVelocity: Metric; xmlVelocity: Metric; velocityGapPct: Metric; velocity: Metric; stockDays: Metric; stockQty: number | null; inboundQty: number | null;
  inboundEta: string | null; inboundBeforeStockout: boolean; openPurchaseOrders: number | null;
  momentum: Metric; pricePeriod: string;
};
export type CfoAgentSnapshot = {
  notebook?: CfoNotebook;
  schemaVersion: string; calculationVersion: string; generatedAt: string; timezone: "Europe/Istanbul";
  currency: "TRY"; accountingBasis: Basis;
  dataQuality: { staleSources: string[]; missingFields: string[]; costCoveragePct: number | null;
    matchingCoveragePct: number | null; sourceWatermarks: SourceWatermark[]; excludedDummyStock: number; zeroStockSkuCount: number; commissionCoverage: {channel:string; coveragePct:number|null; outliers:number}[];
    fbaInventoryUnknown: true; duplicateCanonicalRows: number; excludedUntrustedRows: number };
  sales: { lastHour: SalesPeriod; today: SalesPeriod; yesterday: SalesPeriod; last7Days: SalesPeriod;
    last30Days: SalesPeriod; monthToDate: SalesPeriod; comparisons: Comparison[] };
  profitability: Profitability; profitabilityByPeriod: Record<string, Profitability>; channels: { channel: string; profitability: Profitability; previousMargin: Metric; sourceFresh: boolean; netSettlementRatio: Metric; estimatedNetReceipts: Metric }[];
  inventory: { costValue: Metric; knownCostValue: Metric; retailValue: Metric; stockoutRiskValue: Metric; deadStockValue: Metric };
  products: ProductSignal[];
  deadStock: { sku: string; value: Metric; alarm: string; findingId: string | null }[];
  cash: { generalUnusedOverdraft: Metric; totalCardDebt: Metric; activeCards: number; cash: Metric; minimumProjectedPosition: Metric; purposeLimit: Metric; banksFresh: boolean; summaries: Evidence[] };
  procurement: { riskySkuCount: number; openOrders: number | null };
  importPipeline: { inboundSkuCount: number | null; coveragePct: Metric };
  returns: { currentRate: Metric; previousRate: Metric; sample: number; complete: boolean };
  evidence: Evidence[];
};
export type Anomaly = { id: string; rule: string; severity: Severity; category: Category; entityType: string;
  entityId: string; period: string; fingerprint: string; cooldownKey: string; evidenceIds: string[];
  actionable: boolean; impact: Impact | null; weight: number; existingRecordIds: string[] };
export type AiInsight = { anomalyId: string; severity: Severity; category: Category; title: string;
  observation: string; recommendation: string; riskIfIgnored: string; confidence: "low" | "medium" | "high"; evidenceIds: string[] };
export type MemoryItem = { source: string; entityId: string; text: string; asOf: string };
export type RunType = "monitor" | "morning";
export type ProviderResult = { text: string; inputTokens: number; outputTokens: number; cacheReadTokens: number;
  cacheWriteTokens: number; requestId: string | null };
