import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';
import { ensureRowQuestion } from '../lib/cfo/question-record';
import { questionHref,questionSourceHref } from '../lib/cfo/question-links';
import { researchCfoSources,initialResearch,RESEARCH_PAGE_PATHS } from '../lib/cfo-agent/research';
import { readMemory } from '../lib/cfo-agent/workflow-memory';
import { workflowId } from '../lib/cfo-agent/workflow-plan';
import type { WriteSource } from '../lib/cfo-agent/workflow-store';
import type { Row } from '../lib/cfo-agent/sources';
async function main(){const pg=new PGlite();
  try{
    await pg.exec(`create table cfo_question(id text primary key,question text,why text,area text,priority integer,status text,answer text,"askedAt" timestamptz default now(),scope text,entity_key text,code text);
      create unique index open_row_identity on cfo_question(scope,entity_key,code) where status='ACIK';
      create table "Product"(id text primary key,sku text,"name" text,"isActive" boolean,"productKind" text,"stockQuantity" int,"unitCostTry" numeric,"sourceCostRmb" numeric,"weightKg" numeric,"onlineSalesPotential" numeric);
      insert into "Product" select 'p-'||lpad(i::text,3,'0'),'SYNTH-'||i,'Synthetic item',true,'STANDARD',10,null,null,null,null from generate_series(1,210) i;
      create table cfo_stok_sicrama_durum(id int primary key,sku text,urun text,hareket_gunu date,delta int,durum text,aciklanamayan_adet int,aciklanamayan_maliyet_try numeric,otomatik_teshis text,aciklama text);
      insert into cfo_stok_sicrama_durum values(1,'SYNTH-1','Synthetic','2025-01-01',-2,'ACIK',2,100,'Needs channels',null),(2,'SYNTH-2','Synthetic','2025-01-01',-1,'KAPANDI',0,0,'Verified','Synthetic closure');
      create table urun_aday_skor(id int primary key,sku text,ad_tr text,durum text,puan int,eksikler jsonb,katalogda_var boolean,birim_usd numeric,agirlik_kg numeric,adet int);
      insert into urun_aday_skor values(1,'SYNTH-NEW','Synthetic','TASLAK',60,'["weight"]',false,null,null,10),(2,'SYNTH-REJECT','Synthetic','REDDEDILDI',40,'["weight"]',false,null,null,10);
      create table "MarketplaceProductMapping"(id text primary key,platform text,"productId" text,"platformSku" text,"platformBarcode" text,"platformProductId" text,"platformListingId" text,confidence text);
      insert into "MarketplaceProductMapping" values('m1','TRENDYOL','p-001',null,null,null,null,'MANUAL');
      create table "XmlSyncSource"(id text primary key,name text,"isEnabled" boolean,"lastSyncAt" timestamp,"lastStatus" text,"authHeader" text,url text);
      insert into "XmlSyncSource" values('x1','Synthetic',true,'2025-01-01','FAILED','SECRET-SYNTHETIC-DO-NOT-LOAD','SECRET-SYNTHETIC-DO-NOT-LOAD');
      create table "EntegraImportLog"(id text primary key,"rowCount" int,"createdCount" int,"updatedCount" int,"skippedCount" int,"dateFrom" timestamp,"dateTo" timestamp,"createdAt" timestamp,"userEmail" text);
      insert into "EntegraImportLog" values('u1',10,9,0,1,'2019-01-01','2019-01-31','2025-01-01','SECRET-SYNTHETIC-DO-NOT-LOAD');
      create table "MarketplaceSalesRecord"(id text primary key,channel text,"modelNumber" text,"productId" text,"orderDate" timestamp,"totalAmountTry" numeric,quantity int,status text,"customerTcKimlik" text);
      insert into "MarketplaceSalesRecord" select 's-'||i,'IDEASOFT','ARCHIVE-'||lpad(i::text,3,'0'),null,'2019-01-10',100,1,case when i=1 then 'İade-İptal' else 'Delivered' end,'SECRET-SYNTHETIC-DO-NOT-LOAD' from generate_series(1,310) i;
      insert into "MarketplaceSalesRecord" values('late','IDEASOFT','LATE',null,'2025-01-10',null,2,'Delivered','SECRET-SYNTHETIC-DO-NOT-LOAD');
      create table "TrendyolSalesRecord"(id text primary key,"merchantSku" text,"productId" text,"orderDate" timestamp,"totalPriceTry" numeric,quantity int,status text);
      insert into "TrendyolSalesRecord" values('ty1','SYNTH-1','p-001','2020-01-01',100,1,'Delivered');
      create table "TrendyolReturnRecord"(id text primary key,"merchantSku" text,"productId" text,"claimDate" timestamp,"unitPriceTry" numeric,status text);
      insert into "TrendyolReturnRecord" values('r1','SYNTH-1','p-001','2020-01-02',100,'Rejected');`);
    const queries:string[]=[];
    const db:WriteSource={async query<T extends Row>(sql:string,...params:unknown[]):Promise<T[]>{queries.push(sql);return (await pg.query<T>(sql,params)).rows;},execute:(sql,...params)=>pg.query(sql,params)};
    const input={scope:'ITHALAT_SATIRI',entityKey:'DENIZ|SYNTH-1',code:'MALIYET_YOK',question:'Synthetic cost and weight?',why:'Synthetic import evidence',area:'marj'};
    let q=await ensureRowQuestion(db,input);assert(q.created);
    await db.execute('update cfo_question set answer=$2,status=$3 where id=$1',q.id,'Synthetic owner answer','CEVAPLANDI');
    const same=await ensureRowQuestion(db,{...input,entityKey:'HAVA|synth-1',question:'Do not overwrite the original question'});
    assert.equal(same.id,q.id);assert.equal(same.answer,'Synthetic owner answer');assert(!same.created);
    assert.equal((await db.query('select question from cfo_question where id=$1',q.id))[0].question,input.question);
    await db.execute("update cfo_question set status='IPTAL' where id=$1",q.id);
    assert.equal((await ensureRowQuestion(db,input)).status,'IPTAL','cancellation is never automatically reopened');
    const legacyId=workflowId('question:cost:SYNTH-2');
    await db.execute("insert into cfo_question(id,question,area,priority,status,answer) values($1,'Synthetic old answer','marj',2,'CEVAPLANDI','Synthetic legacy evidence')",legacyId);
    q=await ensureRowQuestion(db,{...input,entityKey:'DENIZ|SYNTH-2'});
    assert.equal(q.id,legacyId);assert.equal(q.answer,'Synthetic legacy evidence');
    assert.equal((await db.query('select scope from cfo_question where id=$1',q.id))[0].scope,'ITHALAT_SATIRI');
    assert(questionHref(q.id).startsWith('/cfo/sorular?question='));assert.equal(questionSourceHref('ITHALAT_SATIRI'),'/cfo/kazananlar#ithalat');
    const asOf='2025-02-01T12:00:00.000Z';
    let result=await researchCfoSources(db,initialResearch(),asOf,new Map([['SYNTH-1',{virtual:true,noReorder:false}]]));
    assert.equal(result.state.sources.catalog.scanned,200);assert(!result.state.sources.catalog.complete);
    assert.equal(result.state.sources['entegra-history'].month,'2019-01');assert(!result.state.sources['entegra-history'].complete);
    assert.equal(result.state.sources['entegra-history'].scanned,300,'oldest historical month is scanned first with keyset continuation');
    assert(!result.items.some(i=>i.key==='research:catalog:p-001:cost'),'virtual stock is excluded from stock capital findings');
    assert(result.items.some(i=>i.key==='research:stock:1:unexplained'));assert(!result.items.some(i=>i.key==='research:stock:2:unexplained'));
    result=await researchCfoSources(db,result.state,asOf);
    assert(result.items.some(i=>i.sku==='SYNTH-NEW'));assert(!result.items.some(i=>i.sku==='SYNTH-REJECT'));
    result=await researchCfoSources(db,result.state,asOf);
    assert(result.items.some(i=>i.key==='research:xml:x1:freshness'));
    assert(!JSON.stringify(result).includes('SECRET-SYNTHETIC-DO-NOT-LOAD'),'customer details and credentials never enter research');
    result=await researchCfoSources(db,result.state,asOf);
    assert.equal(result.state.sources.catalog.scanned,210);assert(result.state.sources.catalog.complete);
    assert.equal(result.state.sources['entegra-history'].month,'2025-01','empty years are skipped without stalling on absent months');
    assert.equal(result.state.sources['entegra-history'].scanned,310);
    const archival=result.items.find(i=>i.key==='research:entegra-history:2019-01')!;
    assert(archival.evidence.some(e=>e.includes('309 iptal/iade dışı adet')));
    assert(archival.evidence.some(e=>e.includes('30900.00 TL')));
    assert(archival.blockers.some(b=>b.includes('birbirine eklenmez')),'overlapping raw sources never become a combined company revenue/profit');
    assert(result.items.some(i=>i.key.endsWith(':site')),'IDEASOFT is included in the historical scan');
    const memory=readMemory(JSON.stringify({agenda:{nextTopic:'stock'},research:{state:result.state}}));
    assert.equal(memory.research?.sources.catalog.scanned,210,'research cursor survives heartbeat serialization');
    assert.equal(RESEARCH_PAGE_PATHS.length,8);for(const url of ['/products?view=importer','/admin/stok-sicrama','/admin/yeni-urunler','/admin/marketplace-mappings','/admin/xml-sync','/admin/entegra-yukleme','/admin/trendyol-report','/orders'])assert(RESEARCH_PAGE_PATHS.includes(url));
    await pg.exec('drop table urun_aday_skor');
    const before=result.state.sources['new-products'].scanned;
    result=await researchCfoSources(db,result.state,asOf);
    assert(!result.state.sources['new-products'].available);assert.equal(result.state.sources['new-products'].scanned,before,'failed reads cannot falsely advance coverage');
    assert(result.state.sources['trendyol-history'].available,'other source work proceeds after one failure');
    assert(!queries.some(sql=>/customerTcKimlik|authHeader|userEmail/.test(sql)));
  }finally{await pg.close();}
  console.log('CFO shared questions and research: identity reuse, answer/cancellation preservation, legacy links, all eight pages, oldest-first resumable history, privacy, raw-source isolation and progress after a failed source passed');
}
main().catch(e=>{console.error(e);process.exitCode=1;});
